import CustomNavbar from "@/components/navbar";
import "./globals.css";
import { NextUIProvider } from "@nextui-org/react";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    // <ApolloProvider>
    <html lang="en">
      <body className={``}>
        <CustomNavbar />

        {/* <ApolloProvider client={client}> */}
        <NextUIProvider>{children}</NextUIProvider>
        {/* </ApolloProvider> */}
      </body>
    </html>
    // </ApolloProvider>
  );
}
